name: Update VPN Configs

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests geoip2 PySocks

      - name: Run VPN Parser Script
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: python main.py

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          git add FL1PVPN stats.json history.json
          
          if git diff --staged --quiet; then
            echo "Changes not detected. Skipping commit."
          else
            git commit -m "🚀 Auto-update: $(date -u)"
            
            # --- FIX: Забираем изменения с удаленного сервера перед отправкой ---
            git pull --rebase origin main
            
            git push
          fi
